{
 "title": "D65",
 "time": { "from": "2025-06-26T14:42:23.776Z", "to": "2025-06-27T04:49:27.306Z" },
 "panels": [
  { "title": "Faults and errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Path request",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"^BPath[1-2].+\",message=~\"^.+_Control\"}",
     "legendFormat": "{{message}}:{{__name__}}"
    },
    {
     "expr": "{__name__=~\"(NState|NPath.State)\"}",
     "legendFormat": "{{message}}:{{__name__}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"^.+B.+(Fault|Error)$\"} > 0",
     "legendFormat": "{{message}}:{{__name__}}"
    }
   ]
  },
  {
   "title": "Fault signal",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 13 },
   "targets": [
    { "expr": "BFaultSignal > 0", "legendFormat": "{{message}}" }
   ]
  },
  {
   "title": "ACUHV Voltage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACUHV Port A1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "{message=~\"^BL[1-4].+PortA1.+\",unit=\"V\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    },
    {
     "title": "ACUHV Port B1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "{message=~\"^BL[1-4].+PortB.+\",unit=\"V\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    },
    {
     "title": "ACUHV Port A2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "{message=~\"^BL[1-4].+PortA2.+\",unit=\"V\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ACUHV Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACUHV Port A1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "{message=~\"BL[1-4].+PortA1.+\",unit=\"A\",__name__=~\"^IdPort.+RMS$\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    },
    {
     "title": "ACUHV Port B1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 377 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "{message=~\"BL[1-4].+PortB1.+\",unit=\"A\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      },
      {
       "expr": "sum({message=~\"BL[1-4].+PortB1.+\",unit=\"A\"})",
       "legendFormat": "Total Current"
      }
     ]
    },
    {
     "title": "ACUHV Port A2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 385 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "{message=~\"BL[1-4].+PortA2.+\",unit=\"A\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      },
      {
       "expr": "sum({message=~\"BL[1-4].+PortA2.+\",unit=\"A\"})",
       "legendFormat": "Total Current"
      }
     ]
    }
   ]
  },
  {
   "title": "DCHVI Voltage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCHVI Port C",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "{message=~\"^BL[5-7].+PortC.+\",unit=\"V\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    },
    {
     "title": "DCHVI Port B1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "{message=~\"^BL[5-7].+PortB.+\",unit=\"V\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    },
    {
     "title": "DCHVI Port A1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "{message=~\"^BL[5-7].+PortA.+\",unit=\"V\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DCHVI Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCHVI Port C",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "{message=~\"BL[5-7].+PortC.+\",unit=\"A\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      },
      {
       "expr": "sum({message=~\"BL[5-7].+PortC.+\",unit=\"A\"})",
       "legendFormat": "Total Current"
      }
     ]
    },
    {
     "title": "DCHVI Port B",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 283 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "{message=~\"BL[5-7].+PortB1.+\",unit=\"A\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      },
      {
       "expr": "sum({message=~\"BL[5-7].+PortB1.+\",unit=\"A\"})",
       "legendFormat": "Total Current"
      }
     ]
    },
    {
     "title": "DCHVI Port A1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "{message=~\"BL[5-7].+PortA1.+\",unit=\"A\"}",
       "legendFormat": "{{message}}:{{__name__}}"
      },
      {
       "expr": "sum({message=~\"BL[5-7].+PortA1.+\",unit=\"A\"})",
       "legendFormat": "Total Current"
      }
     ]
    }
   ]
  },
  {
   "title": "Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compressor Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "VCU_CP1_Speed_Command or CP1_Motor_Speed or CP2_Motor_Speed",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Compressor Torque",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
     "fieldConfig": { "defaults": { "unit": "forceNm" } },
     "targets": [
      {
       "expr": "{message=~\"(CP1.+Command_Message|CP[1-2].+Torque.+)\",unit=\"torque:N.m\",__name__!=\"VCU_CP1_Torque_Command\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hydraulics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hydraulics Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "VCU_HYD_Speed_Command or HYD_Motor_Speed",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Hydraulics Torque",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "forceNm" } },
     "targets": [
      {
       "expr": "{message=\"HYD_Torque_And_Timer_Info\",unit=\"torque:N.m\"}",
       "legendFormat": "{{__name__}}"
      },
      { "expr": "VCU_HYD_Torque_Limit_Command", "legendFormat": "{{__name__}}" }
     ]
    }
   ]
  },
  {
   "title": "Fan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "VCU_FAN_Speed_Command or FAN_Motor_Speed",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Fan Torque",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "forceNm" } },
     "targets": [
      {
       "expr": "{message=\"FAN_Torque_And_Timer_Info\",unit=\"torque:N.m\"}",
       "legendFormat": "{{__name__}}"
      },
      { "expr": "VCU_FAN_Torque_Limit_Command", "legendFormat": "{{__name__}}" }
     ]
    }
   ]
  },
  { "title": "Cable Reel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Cable Reel I/O",
   "type": "status-history",
   "gridPos": { "h": 25, "w": 14, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{__name__=~\"C2S_cr.+cmd\"} or {__name__=~\"S2C_ScreenCr.+\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"C2S_cr.+\",__name__!~\"C2S_cr.+cmd\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}